# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  newsletter-api:
    build:
      context: "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\\
        after\\ContentPlatform"
      dockerfile: "Newsletter.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "newsletter-api:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "C:\\Users\\diego\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\diego\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\after\\\
      ContentPlatform\\Newsletter.Api:/app:rw"
    - "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\after\\\
      ContentPlatform:/src:rw"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\Installations\\Rider233\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_28_09_14_35:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  newsletter-reporting-api:
    build:
      context: "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\\
        after\\ContentPlatform"
      dockerfile: "Newsletter.Reporting.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "newsletter-reporting-api:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\diego\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\after\\\
      ContentPlatform\\Newsletter.Reporting.Api:/app:rw"
    - "D:\\Src\\Milan\\Asynchronous Request Response Pattern with MassTransit\\after\\\
      ContentPlatform:/src:rw"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\Installations\\Rider233\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\diego\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_28_09_14_35:/var/opt/rider-debugger:rw"
    working_dir: "/app"
