version: '3.4'

services:
  newsletter-api:
    image: ${DOCKER_REGISTRY-}newsletter-api
    container_name: Newsletter.Api
    build:
      context: .
      dockerfile: Newsletter.Api/Dockerfile
   
  newsletter-reporting-api:
    image: ${DOCKER_REGISTRY-}newsletter-reporting-api
    container_name: Newsletter.Reporting.Api
    build:
      context: .
      dockerfile: Newsletter.Reporting.Api/Dockerfile
   
  newsletter-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: newsletter-db
    hostname: newsletter-db

  #Updated
  newsletter-mq:
    image: rabbitmq:management
    container_name: Newsletter.RabbitMq
    hostname: newsletter-mq